version: '3.7'
services:
  mariadb:
    image: alpine-mariadb-42
    networks:
      - global
    volumes:
      - wordpressDB:/volumes/wordpressDB
    environment:
      - WordpressDBName
      - WordpressDBUser
      - WordpressDBPass
      - MariaDBRootPassword
    build:
      context: ./mariadb
    restart: always
  php:
    depends_on:
      - mariadb
    image: alpine-php-42
    networks:
      - global
    volumes:
      - wordpressFiles:/volumes/wordpressFiles
    environment:
      - WordpressDBName
      - WordpressDBUser
      - WordpressDBPass
    build:
      context: ./php
    restart: always
  nginx:
    depends_on:
      - php
    image: alpine-nginx-42
    ports:
      - "443:443"
    networks:
      - global
    volumes:
      - wordpressFiles:/volumes/wordpressFiles
    build:
      context: ./nginx
    restart: always

networks:
  global:

volumes:
  wordpressFiles:
  wordpressDB:
