version: '3.7'
services:
  mariadb:
    image: alpine-mariadb-42
    container_name: "mariadb"
    networks:
      - inception
    volumes:
      - wordpressDB:/volumes/wordpressDB
    environment:
      - WordpressDBName
      - WordpressDBUser
      - WordpressDBPass
      - MariaDBRootPassword
    build:
      context: ./mariadb
    restart: always
  php:
    image: alpine-php-42
    container_name: "php"
    networks:
      - inception
    volumes:
      - wordpressFiles:/volumes/wordpressFiles
    environment:
      - WordpressDBName
      - WordpressDBUser
      - WordpressDBPass
      - WP_CLI_CONFIG_PATH
    build:
      context: ./php
    restart: always
  nginx:
    image: alpine-nginx-42
    container_name: "nginx"
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpressFiles:/volumes/wordpressFiles
    build:
      context: ./nginx
    restart: always

networks:
  inception:
    name: "inception"

volumes:
  wordpressFiles:
  wordpressDB:
