services:
  nginx:
    image: alpine-nginx-42
    ports:
      - "80:80"
    networks:
      global:
        ipv4_address: 172.20.2.1
    volumes:
      - test:/test
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
  php:
    image: alpine-php-42
    networks:
      global:
        ipv4_address: 172.20.2.2
    volumes:
      - test:/test
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: always
  mariadb:
    image: alpine-mariadb-42
    networks:
      global:
        ipv4_address: 172.20.2.3
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    restart: always

networks:
  global:
    ipam:
      driver: default
      config:
        - subnet: "172.20.2.0/16"
volumes:
  test:
